### ISSUE TITLE
Help sir

### ISSUE THREAD

**Issue by Araara7** [mativusgf/gradient-network-bot#1]
what happend with this ?
Error occurred (Attempt 1/5): max() arg is an empty sequence

**Comment by mativusgf** [comment]
> what happend with this ? Error occurred (Attempt 1/5): max() arg is an empty sequence

Hello! Check if pip "setuptools" is installed, without it you are getting the same error as yours. And let me know if it fixed the problem?

**Comment by Araara7** [comment]
i already installed sir with command pip install -r requirements.txt

**Comment by Araara7** [comment]
![image](https://github.com/user-attachments/assets/89a669b8-36ad-4ad1-a7de-12e59a316056)

**Comment by mativusgf** [comment]
Now I see what the problem is. This problem sometimes happens with untedeteckted chromedriver. This is the only solution I've found:

Replace
"driver = uc.Chrome(seleniumwire_options=proxy_options, options=chrome_options, user_data_dir=user_data_dir, user_multi_procs=True, use_subprocess=True)"
with 
"driver = uc.Chrome(options=chrome_options)",
run the script, and after the script starts, stop execution and return everything as it was. No more problems with untedeteckted chromedriver.

If you find another solution with untedeteckted chromedriver, let me know, I will make changes.

> ![image](https://private-user-images.githubusercontent.com/90325194/384599394-89a669b8-36ad-4ad1-a7de-12e59a316056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNTI1NzYsIm5iZiI6MTczMTE1MjI3NiwicGF0aCI6Ii85MDMyNTE5NC8zODQ1OTkzOTQtODlhNjY5YjgtMzZhZC00YWQxLWE3ZGUtMTJlNTlhMzE2MDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDExMzc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5YTM0ZDU0ZDJhY2ZlMzg0MDUzN2Q0OWMwZDQwNzQ5NzMwZjM3YmU5ZGM3NzVlYTVjZTY0NGE3ODZmMTBjNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f-8eG3DiwrbTC3qCVkKgc-DsSc-60C_ROQMgOR2gC8Q)

**Comment by bscongluanbui** [comment]
> Now I see what the problem is. This problem sometimes happens with untedeteckted chromedriver. This is the only solution I've found:
> 
> Replace "driver = uc.Chrome(seleniumwire_options=proxy_options, options=chrome_options, user_data_dir=user_data_dir, user_multi_procs=True, use_subprocess=True)" with "driver = uc.Chrome(options=chrome_options)", run the script, and after the script starts, stop execution and return everything as it was. No more problems with untedeteckted chromedriver.
> 
> If you find another solution with untedeteckted chromedriver, let me know, I will make changes.
> 
> > ![image](https://private-user-images.githubusercontent.com/90325194/384599394-89a669b8-36ad-4ad1-a7de-12e59a316056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNTI1NzYsIm5iZiI6MTczMTE1MjI3NiwicGF0aCI6Ii85MDMyNTE5NC8zODQ1OTkzOTQtODlhNjY5YjgtMzZhZC00YWQxLWE3ZGUtMTJlNTlhMzE2MDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDExMzc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5YTM0ZDU0ZDJhY2ZlMzg0MDUzN2Q0OWMwZDQwNzQ5NzMwZjM3YmU5ZGM3NzVlYTVjZTY0NGE3ODZmMTBjNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f-8eG3DiwrbTC3qCVkKgc-DsSc-60C_ROQMgOR2gC8Q)

where to edit it sir. Main.py?

**Comment by mativusgf** [comment]
> where to edit it sir. Main.py?

Yes. In the setup_driver function at the very end of the function before return.

**Comment by bscongluanbui** [comment]
> run the script, and after the script starts, stop execution and return everything as it was. No more problems with untedeteckted chromedriver.

another errors is
patching driver executable /home/ubuntu/.local/share/undetected_chromedriver/undetected_chromedriver
Error occurred (Attempt 1/5): [Errno 8] Exec format error: '/home/ubuntu/.local/share/undetected_chromedriver/undetected_chromedriver'

**Comment by MHendriF** [comment]
Can this code run on linux vps?

**Comment by mativusgf** [comment]
> Can this code run on linux vps?

Yes, but provided Chrome is installed on the VPS

**Comment by candrawibowo** [comment]
Hi, i just found new bugs after Replace
"driver = uc.Chrome(seleniumwire_options=proxy_options, options=chrome_options, user_data_dir=user_data_dir, user_multi_procs=True, use_subprocess=True)"
with
"driver = uc.Chrome(options=chrome_options)",
run the script, and after the script starts, stop execution and return everything as it was. No more problems with untedeteckted chromedriver.

2024-11-10 16:17:35,176 - ERROR - [email@gmail.com] Error occurred (Attempt 2/10): name 'driver' is not defined

**Comment by maianhbao1** [comment]
Have you fixed the error yet sir?
![Screenshot 2024-11-12 111158](https://github.com/user-attachments/assets/052475f0-497d-496f-96a2-073e66a004b3)
