### ISSUE TITLE
error

### ISSUE THREAD

**Issue by WP1223** [mativusgf/gradient-network-bot#4]
why error?
![Screenshot 2024-11-11 092915](https://github.com/user-attachments/assets/d7375a27-dcbd-4043-a044-544d0fde1d25)

**Comment by mativusgf** [comment]
Please, check this issue:
https://github.com/mativusgf/gradient-network-bot/issues/1

**Comment by WP1223** [comment]
still error sir

**Comment by WP1223** [comment]
![image](https://github.com/user-attachments/assets/05721132-4e32-47bd-af3f-62afffbe7090)
run or no??

**Comment by mativusgf** [comment]
> ![image](https://private-user-images.githubusercontent.com/177915112/384828637-05721132-4e32-47bd-af3f-62afffbe7090.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTA5OTAsIm5iZiI6MTczMTMxMDY5MCwicGF0aCI6Ii8xNzc5MTUxMTIvMzg0ODI4NjM3LTA1NzIxMTMyLTRlMzItNDdiZC1hZjNmLTYyYWZmZmJlNzA5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwNzM4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjJiY2Y4NDUzZDkyOWU5MGI5OWRlZWNjMmNlOGJhODQwNzJjYWUwYmMzNjlkYTg3ZmI5MWVmYWY4Yjk2ZTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DyOfrelYZ_VIJLeeE_tJX2V7gqAp9MKiiZKBzj9BuXQ) run or no??

Yes

**Comment by WP1223** [comment]
why proxy not detected sir
